JIP-295 FEATURE: 예약 대출 문구 수정
jiphyeonjeon-42/frontend pull request #198
Opened 2022-07-03 19:27 UTC by YeonSeong-Lee

### 개요
 예약 1순위여도, 아직 책을 부여받지 않았을 수도 있습니다.

현재 예약 0순위라고 되어있는데 지금 동작은 책을 할당받은 예약들만 보여주고 있습니다. (원래 pending), 이는 사서들에게 혼돈을 줄 수 있어 수정이 필요합니다.

### 지라 링크
https://42jiphyeonjeon.atlassian.net/browse/JIP-295?atlOrigin=eyJpIjoiNzdiODA4YzIwMWM2NDdlMTgyMjQ2NDljNWIxODc4YWYiLCJwIjoiaiJ9

### 스크린샷
![image](https://user-images.githubusercontent.com/62806979/177054494-d90393a7-231e-4638-9030-530b71a5dc4a.png)

2022-07-04 07:48 UTC, kth2624 approved these changes
확인했습니다.

2022-07-04 07:49 UTC, keinn51 requested changes
티킴님이 잘못 누르셨습니다..!

2022-07-05 10:49 UTC, keinn51 reviewed
사서 회의에서 결정한 이후에 어떻게 수정할 지에 대해서 대화를 나누어보겠습니다.

2022-07-16 15:05 UTC, YeonSeong-Lee commented
기각

2022-07-16 15:05 UTC, closed without merging