Jip 299 도서 상세 title css 및 기부자 표시 수정
jiphyeonjeon-42/frontend pull request #200
Opened 2022-07-04 09:03 UTC by Jiwon-Woo

### 1. title
`도서 상세페이지 및 예약` -> `도서 상세 및 예약` 으로 수정했습니다.

### 2. 기부자 표시
`,` 붙이는 로직이 잘못되어 수정했습니다.

### 3. css
태블릿 화면에서의 글자크기와 여백을 조정했습니다.

### 4. 에러메세지
에러 메세지 띄우는 방법을 수정했습니다

2022-07-05 05:39 UTC, YeonSeong-Lee commented on src/component/book/BookDetail.js
>    let history = useHistory();
주석처리를 이용해서 `let`을 사용한 이유가 궁금합니다.

2022-07-05 05:41 UTC, YeonSeong-Lee commented on src/component/book/BookDetail.js
>    let history = useHistory();
주석처리를 이용하면서 `let`을 사용한 이유가 궁금합니다.

2022-07-05 06:11 UTC, Jiwon-Woo commented on src/component/book/BookDetail.js
>    let history = useHistory();
처음 본 가이드를 쭉 따라해서 생긴 습관인거 같네요
추후에 한번에 고쳐서 올리도록 하겠습니다!

2022-07-05 10:48 UTC, keinn51 commented on src/component/book/BookDetail.js
> +    else if (!user.isLogin) history.push("/login");
여기서 user을 쓰는 데에도 위에서 unused 에 대한 주석처리를 해줘야 하나요?

2022-07-06 02:00 UTC, keinn51 commented on src/component/book/BookDetail.js
> +    else if (!user.isLogin) history.push("/login");
그럼 이 것에 대한 것들은 나중에 지우기로 하고 저는 어프루브를 하겠습니당

2022-07-06 02:02 UTC, keinn51 approved these changes
주석처리만 나중에 지우면 될 것 같습니다. 굿굿 수고하셨어욤

2022-07-06 02:02 UTC, keinn51 commented on src/data/error.js
> +      return `로그인 후 이용할 수 있는 기능입니다.`;
디테일 굿굿

2022-07-06 02:02 UTC, keinn51 commented on src/css/BookDetail.css
> +/* .book-detail__info > div:first-child {
요런 것들도 하다가 안 지우신거쥬??

2022-07-06 02:05 UTC, YeonSeong-Lee commented
그냥 깔끔하게 정리하고 머지 합시다.

2022-07-06 02:40 UTC, keinn51 commented
> 깔끔하게 정리하고 머지 합시다.

그게 좋을 수도 있겠군요 주석 지우는 것이 어려운 일은 아니니까..! 그럼 체인지 리퀘스트로...

2022-07-06 02:40 UTC, keinn51 requested changes
주석 수정만 후다닥 해주십시오~!

2022-07-06 05:21 UTC, Jiwon-Woo commented
피드백 반영 완료~!

2022-07-06 06:51 UTC, keinn51 approved these changes
주석 처리 확인했습니다!

2022-07-06 08:45 UTC, merged