JIP-313 메인 신작도서 이미지 조절 및 깨진 이미지 대체
jiphyeonjeon-42/frontend pull request #209
Opened 2022-07-07 09:04 UTC by notusing11

## 요약
모바일 화면에서 메인페이지의 신작도서 이미지가 작아지도록 변경하였습니다
<img width="502" alt="image" src="https://user-images.githubusercontent.com/74622889/177724241-08950a5d-2676-4890-9601-c2c1d723d986.png">

## 수정사항
- css 대신 js 파일에서 width 설정하도록 변경했습니다
- window.innerWidth를 감지해서 모바일 화면일때 width를 줄여줍니다.
- js 컴포넌트마다 역할을 분명히 했습니다 

### 컴포넌트 별 역할
- mainNew : api 호출 및 데이터 저장
- mainNewBookList : 버튼 및 이벤트 동작 설정
- mainNewBook : 책 노출 방식 결정 이미지가 없는 경우 회색 면으로 대체

2022-07-07 15:43 UTC, keinn51 approved these changes
매력적인 로직과 커스텀 훅 잘 봤습니다 굿굿~

2022-07-07 15:43 UTC, keinn51 commented on src/component/main/MainNewBookList.js
> +function useWidth() {
![ezgif com-gif-maker](https://user-images.githubusercontent.com/79993356/177814066-30dec34d-69dd-435e-bbb9-b062512255ca.gif)

와.. 수지킴님 custom hook도 만들어서 쓰십니까? 대단합니다... 일반 함수에서 hook이 어떻게 써지지? 하고 봤는데 직접 훅을 만들어서 집어넣으신거군요? (고수다!)

아 그리고 지금 방식에서 개인적으로 아쉬웠던 점이 있었는떼 어쩔 수 없이 화면을 줄이거나 늘일 때에 엄청난 리렌더링이 난다는 부분이 있습니다.. 근데 로직상 저도 더 나은 방법을 생각하기 힘드네여

2022-07-08 05:47 UTC, keinn51 requested changes
useEffect 안에 window.innerWidth 를 넣지 말고 이를 handleSize 안에다가 넣어야 합니다!

2022-07-08 12:10 UTC, notusing11 commented
좋은 의견 감사합니다!


불필요한 상태변화가 많았던 것 같습니다
랜더링 횟수를 줄이면서 코드도 많이 정리했습니다. 
![Jul-08-2022 21-09-03](https://user-images.githubusercontent.com/74622889/177989435-3d2acaff-5b39-45a4-9ac3-445bb57d43ac.gif)

2022-07-09 10:45 UTC, tmam444 approved these changes
PC 너비, 모바일 너비 변수 설정 및 resize 이벤트시 핸들러를 작동시키는 형태 이해했습니다!

2022-07-10 08:40 UTC, keinn51 approved these changes
지난 번 이후 수정사항 확인했습니다. if 문을 이벤트 핸들러 안에 둔 것 확인!

2022-07-10 09:17 UTC, merged