FIX: fix the comment in popular books section
jiphyeonjeon-42/frontend pull request #265
Opened 2022-09-28 22:59 UTC by jae-hwan-kim

* Before
![image](https://user-images.githubusercontent.com/85930183/192903067-249afa7d-4dc6-45ca-b6a7-ccb394a8dcde.png)

* After 
<img width="603" alt="image" src="https://user-images.githubusercontent.com/85930183/192903129-47055b9d-a642-41e5-872e-f3c26090bdc2.png">

2022-09-29 00:43 UTC, keinn51 commented on src/component/main/MainPopular.js
> +          subTitle="42일 인기 도서를 소개합니다"
오호 이제 42일로 바뀌었군욤

2022-09-29 04:24 UTC, YeonSeong-Lee approved these changes
LGTM

gitignore에 package-lock.json을 넣어놔야겠네요.

2022-10-05 09:34 UTC, notusing11 commented
> LGTM
> 
> gitignore에 package-lock.json을 넣어놔야겠네요.

검색해보니 package-lock.json은 삭제하지 않는게 좋다고 합니다! 
모두가 동일한 node_modules 를 갖게 해준다고 하네요

레퍼런스 
https://hyunjun19.github.io/2018/03/23/package-lock-why-need/
https://dschci.tistory.com/108

2022-10-05 09:37 UTC, notusing11 requested changes
커밋 컨벤션 확인부탁드립니다!
package-lock.json 파일도 제외해주시면 좋을 거 같아요

2022-10-06 05:35 UTC, notusing11 approved these changes
커밋메세지 수정 및 package-lock.json 제외된 점 확인했습니다! 
감사합니다👍

2022-10-11 06:34 UTC, merged