feat: tooltip UI 위치 및 크기 확인 훅 구현 (#419)
jiphyeonjeon-42/frontend pull request #425
Opened 2023-04-20 11:17 UTC by notusing11

# 개요
- fixes #419 

- 기본적인 내용만 구현했습니다.
- 위치 지정 기능은 추후에 진행하면 좋을 것 같습니다.

### example
```
import Tooltip from "component/utils/Tooltip";

 <Tooltip description="추가하고자 하는 설명을 여기에 추가하면 됩니다">
  <p>Hover</p>
</Tooltip>
```
### preview
![Apr-20-2023 20-07-26](https://user-images.githubusercontent.com/74622889/233349890-dbd34506-2335-4a7a-90ee-394efe82fdc8.gif)

2023-04-21 10:51 UTC, scarf005 requested changes
수고 많으셨습니다! 올바르게 모달을 구현하려면 많은 노력이 드는 것 같네요

2023-04-21 10:51 UTC, scarf005 commented on src/component/utils/Modal.tsx
useEffect 후크에서 overflow 설정과 ESC 이벤트 등록을 동시에 하는 대신 div에서 onKeyDown으로 ESC 이벤트 등록을 하고 useEffect에서는 [overflow 설정](https://github.com/mdgarden/CS-wiki/issues/29)만 하는 것이 좋을 것 같습니다.
```ts
  useEffect(() => {
    document.body.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = "unset";
    };
  }, []);
```

```ts
import { KeyboardEvent } from "react";
// ...
  const closeModalWithESC = ({ key }: KeyboardEvent<HTMLDivElement>) => {
    if (key === "Escape") onCloseModal();
  };
```

2023-04-21 10:51 UTC, scarf005 commented on src/component/utils/Modal.tsx
> +          aria-hidden="true"
```suggestion
          role="dialog"
          aria-modal="true"
```
모달용 aria 태그가 있다고 합니다. 사용해보면 좋을 것 같습니다.
참고 링크:
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal

2023-04-21 10:51 UTC, scarf005 commented on src/component/utils/Modal.tsx
> +          onClick={closeModal}
```suggestion
          onClick={closeModal}
          onKeyDown={closeModalWithESC}
```
ESC 이벤트를 `onKeyDown`에서 처리하면 어떨까요?

2023-04-21 10:53 UTC, scarf005 commented
![image](https://user-images.githubusercontent.com/54838975/233618384-c137a911-45a0-4786-8a35-21b71b3315af.png)

혹시 PR 제목에 해결 이슈 목록도 함께 적는 컨벤션이 있을까요? PR 번호와 이슈 번호가 함께 있기보다는 PR 번호만 보이도록 제목을 수정한다면 읽는데 도움이 될 것 같습니다!

2023-05-03 06:05 UTC, notusing11 commented on src/component/utils/Modal.tsx
> +  children: React.ReactNode;
의견 감사합니다! 타입스크립트 오류만 없애는 작업만 진행해서 이런 디테일을 신경쓰지 못했었네요!  바로 반영하겠습니다~

2023-05-03 06:07 UTC, notusing11 commented on src/component/utils/Modal.tsx
> +  size: string;
좋습니다! 확실히 자동화로 prop-type 바꾸는건 이런 부분을 다 고려하지 못하는 것 같습니다
모든 컴포넌트 하나씩 다 검토가 필요하겠네요
이 부분도 반영하겠습니다!

2023-05-03 06:16 UTC, notusing11 commented on src/component/utils/Modal.tsx
div의 onKeyDown 이벤트는 해당 div에 포커싱이 된 상황에서만 발생합니다
esc 키로 모달이 닫히는 기능은 포커싱과 상관없이 작동하는게 더 적절하다고 생각합니다.

window 객체에 이벤트를 등록하는 코드로 유지하겠습니다!

2023-05-03 06:17 UTC, notusing11 commented on src/component/utils/Modal.tsx
>    useEffect(() => {}, []);
확인했습니다!

2023-05-03 06:18 UTC, notusing11 commented on src/component/utils/Modal.tsx
> +          onClick={closeModal}
https://github.com/jiphyeonjeon-42/frontend/pull/425/files#r1183275747

여기서 언급했듯 해당 기능은 포커싱에 상관없이 작동하길 기대하고 있어서
div의 onKeyDown보다는 window 객체의 이벤트가 더 적절하다고 생각합니다!

2023-05-03 06:32 UTC, notusing11 commented on src/component/utils/Modal.tsx
> +          aria-hidden="true"
해당 코드는 backdrop이 큰 의미없이 배경으로 깔리는 검은 화면이라 접근성에서 고려하지 않기 위해 aria-hidden 옵션을 준 코드입니다
실제 모달로 작동하는 부분은 다른 곳입니다
role="dialog" 옵션 등은 그 아래 67번 div 쪽으로 추가하겠습니다!!


다만 언급하신 레퍼런스에도 기재되어 있지만 modal 접근성은 단순히 role과 aria 옵션만으로 해결되는게 아니라 더 개선이 필요할 것 같습니다. 
특히 포커싱 관리가 제대로 되지 않아서 접근성을 고려한 모달로는 부족한 점이 아직 남아있네요
앞으로 차근차근 추가해보시죠!!!

2023-05-03 06:52 UTC, notusing11 commented on src/component/utils/Modal.tsx
> +  onCloseModal(): void;
함수인 점을 명시하는 게 더 좋겠네요! 감사합니다!

2023-05-10 03:35 UTC, scarf005 approved these changes

2023-05-13 06:07 UTC, merged