WIP
jiphyeonjeon-42/frontend pull request #620
Opened 2024-09-14 07:33 UTC by hyeunkim42

# 개요

- fixes #

2024-09-22 10:48 UTC, YeonSeong-Lee requested changes

2024-09-22 10:48 UTC, YeonSeong-Lee commented on src/component/rent/RentInquireBoxUser.tsx
> +    const lendingLimit = librarian && librarian.id === selectedUser.id ? 4 : 2;
이 부분이 반복되는데 함수도 빼면 가독성이 더 좋을거 같아요.

2024-09-22 10:48 UTC, YeonSeong-Lee commented on src/component/rent/RentModalConfirm.tsx
> +            <p className="font-16 color-54">{`현재 대출권수 ( ${selectedUser.lendings.length} / ${selectedUser.role === 2 ? '4' : '2'} )`}</p>
```suggestion
            <p className="font-16 color-54">{`현재 대출권수 ( ${selectedUser.lendings.length} / ${selectedUser.role >= 2 ? '4' : '2'} )`}</p>
```

DB에는 3번이라고 "기타 운영진"이라는 상태가 하나 더 있어서 사서만 대출해줄게 아니라 기타 운영진도 4권 대출해줄려면 등호가 부등호로 바뀌어야합니다. 물론 지금은 고려 안 해도 되는 문제!

(p.s. 아주 예전에... 사서가 아닌 스태프도 운영에 참가할 수 도 있었던 시설의 레거시입니다.. 현재는 사문화되었지만...)

+

아래에 있는 변수를 enum으로 바꾸어서 사용해서 매직넘버를 없애봐도 좋을거 같네요.
`ex) userRoleStatusEnum["사서"] // 2`

```
// src/constant/status.js
export const userRoleStatus = [
  { code: 0, string: "미인증" },
  { code: 1, string: "카뎃" },
  { code: 2, string: "사서" },
  { code: 3, string: "기타 운영진" },
];
```

2024-09-22 10:48 UTC, YeonSeong-Lee commented on src/component/rent/RentModalUserList.tsx
> +  const librarian = useRecoilValue(userAtom);
```suggestion
  const currentUser= useRecoilValue(userAtom);
```
`librarian` 는 사서유저를 뜻하는데, 맥락상 사서유저보다는 현재유저가 더 적합한거 같습니다. 

`librarian`으로 하는 특별한 이유가 있나요?!

2024-09-22 10:48 UTC, YeonSeong-Lee commented on src/component/rent/Rent.tsx
```suggestion
/**
 * `Rent` 컴포넌트는 도서 대출 기능을 제공하는 페이지입니다.
 * @description
 * 
 * 유의점:
 * - 사서의 대출권수 4권으로 설정. 사서 본인의 대출건만 4권으로 적용 
 * 
 * 상태:
 * - `selectedUser`: 대출해줄 사용자 정보
 * - `selectedBooks`: 대출해줄 도서 목록
 * 
 * 훅:
 * - `useModal`: 모달 창 열기 및 닫기 기능 제공
 * - `useRecoilValue`: Recoil 상태 관리 라이브러리에서 현재 사용자 정보 가져오기
 *
 * @returns {JSX.Element} 도서 대출 페이지를 렌더링하는 JSX 요소
 */
 
```

JSDoc을 통해 다른 파일에서도 비지니스 로직(사서만 4권)을 확인할 수 있도록 수정하면 유지보수하기 용이할 듯 합니다.

2024-09-23 08:15 UTC, mixsung commented on src/component/rent/RentModalConfirm.tsx
> +            <p className="font-16 color-54">{`현재 대출권수 ( ${selectedUser.lendings.length} / ${selectedUser.role === 2 ? '4' : '2'} )`}</p>
저도 코드 작성할 때 아쉬웠는데 방법 알려주셔서 감사합니다. 반영 후에 다른 피드백이 있다면 또 알려주세요!

2024-09-23 08:17 UTC, mixsung commented on src/component/rent/Rent.tsx
반영했습니다!

2024-09-23 08:43 UTC, mixsung commented on src/component/rent/RentInquireBoxUser.tsx
> +    const lendingLimit = librarian && librarian.id === selectedUser.id ? 4 : 2;
constant의 status.js에 함수화 시켜서 넣어봤습니다. 해당 함수에 객체를 인자로 넘기는데, 객체의 요소(isAdmin이나 id)가 undefined 같은 빈 값으로 들어오는 것도 고려해야 좋은지 고민이 됩니다.

2024-09-23 12:00 UTC, YeonSeong-Lee approved these changes

2024-09-27 06:37 UTC, YeonSeong-Lee commented on src/constant/status.js
> +  return (currentUser.isAdmin && currentUser.id === selectedUser?.id ? 4 : 2);
```suggestion
  return (currentUser?.isAdmin && currentUser.id === selectedUser?.id ? 4 : 2);
```

2024-09-27 06:40 UTC, YeonSeong-Lee commented on src/component/rent/RentInquireBoxUser.tsx
> +    const lendingLimit = librarian && librarian.id === selectedUser.id ? 4 : 2;
이 코멘트를 늦게 봤네요.. 
아래 제안사항과 같이 [옵셔널 체이닝](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)을 이용하면 `undefined`에서 접근할 때 터지는 걸 예방할 수 있어서 옵셔널 체이닝으로 해두고, 값 검증이 필요할 때 타입을 추후에 추가하거나 하면 좋을 거 같습니다.

https://github.com/jiphyeonjeon-42/frontend/pull/620/files#r1778081559

2024-09-27 08:28 UTC, merged